volumes:
  mongo:

services:
  gotenberg:
    image: gotenberg/gotenberg:8
    restart: unless-stopped

  backend:
    build: .
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./files:/app/files
    environment:
      JWT_SECRET: ${JWT_SECRET}
      SERVICE_KEY: ${SERVICE_KEY}
      EXPO_ACCESS_TOKEN: ${EXPO_ACCESS_TOKEN}
      MONGODB_URI: ${MONGODB_URI}
      NOTIFYBOT_URL: ${NOTIFYBOT_URL}