volumes:
  mongo:

services:
  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - mongo:/data/db
    command: ["--replSet", "rs0", "--bind_ip_all"]
    healthcheck:
      test: >
        mongosh --quiet --eval "try { rs.status().ok } catch (e) {
        rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: 'mongo:27017' }] }).ok }"
      retries: 10
      timeout: 10s
      interval: 10s
      start_period: 20s

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH: false
      ME_CONFIG_MONGODB_URL: mongodb://mongo

  gotenberg:
    image: gotenberg/gotenberg:8
    restart: unless-stopped

  backend:
    build: .
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - 3000:3000
    volumes:
      - ./files:/app/files
    environment:
      NOTIFYBOT_URL: ${NOTIFYBOT_URL}
      INTERNAL_URL: http://backend:3000
      GOTENBERG_URL: http://gotenberg:3000
      JWT_SECRET: thisisabadsecretthisisabadsecret
      MONGODB_URI: mongodb://mongo/ClickPrint?authSource=admin